CREATE EVENT test_event_03
ON SCHEDULE EVERY 14 SECOND
ON COMPLETION PRESERVE
STARTS CURRENT_TIMESTAMP
ENDS CURRENT_TIMESTAMP + INTERVAL 1 MINUTE
DO
   INSERT INTO messages(message,created_at)
   VALUES('Test MySQL recurring Event',NOW());

SET GLOBAL event_scheduler = ON;
